### ISSUE TITLE
Future status and timeline for App Data (Documentation)

### ISSUE THREAD

**Issue by yccheok** [gsuitedevs/android-samples#103]
## Expected Behavior
Since, a lot of Android apps are storing their application data in Google Drive App Data folder, it is fair to let developers know up-front, on what is the future status of App Data folder. According to documentation in https://developers.google.com/drive/android/deprecation

> Support for storing and syncing in the app data folder will likely be removed from Drive in the future. Clients requiring app data storage are strongly encouraged to migrate to a non-Drive solution such as Cloud Firestore.

Migrate over to non-Drive solution requires a huge investment effort. It is fair, to let developers know when will App Data be deprecated.

## Actual Behavior

Know the future status and timeline for App Data folder.

**Comment by rbstarbuck** [comment]
There is currently no timeline and no guarantee that app data support will be removed from Drive. However, it is a strong possibility. We are recommending that clients who already need to migrate away from the Android API simply migrate off of Drive altogether if they require app data support, as it will likely prevent a second migration effort down the road.
