### ISSUE TITLE
Getting Error /com.google.android.gms.drive.sample.demo E/CreateEmptyFileActivity: Unable to create file     com.google.android.gms.common.api.ApiException: 17: API: Drive.API_CONNECTIONLESS is not available on this device.

### ISSUE THREAD

**Issue by pa1shetty** [gsuitedevs/android-samples#113]
Getting an error 2019-05-16 15:33:52.451 13382-13382/com.google.android.gms.drive.sample.demo E/CreateEmptyFileActivity: Unable to create file
    com.google.android.gms.common.api.ApiException: 17: API: Drive.API_CONNECTIONLESS is not available on this device.

when I try to create some files.

**Comment by erickoledadevrel** [comment]
Some folks claim you can resolve the issue by making sure the Drive API is enabled in your project:

https://stackoverflow.com/a/49782012/702875

The Drive Android client is deprecated however, so you should probably not built something new on top of it.

**Comment by pa1shetty** [comment]
Drive API was enabled still getting the error. maybe it happening because of depreciation.
