### ISSUE TITLE
Question: Google Drive Application Specific Folder Deprecation

### ISSUE THREAD

**Issue by robsmall** [gsuitedevs/android-samples#117]
As per [Google's Documentation](https://developers.google.com/drive/android/deprecation):

> Support for storing and syncing in the app data folder will likely be removed from Drive in the future. Clients requiring app data storage are strongly encouraged to migrate to a non-Drive solution such as Cloud Firestore.

Is there any timeline around this change? We (Duo Security) are currently storing data in the application specific folder due to security reasons and would like to continue doing so, if possible. If we cannot, then we need to come up with another solution (similar to what is mentioned in the documentation linked above).

As a follow up, will apps still be able to read from the application specific folder after support is removed but not write to it, or will reading from it also no longer be possible?

**Comment by rbstarbuck** [comment]
There is currently no timeline for this change, and it is not yet known whether we'll move forward with it at all (we may continue to support app data). However, we recommend Drive Android API users to migrate to another solution to avoid a second migration effort later, just in case.

Specifics w/r/t whether read access will continue are unknown, but I imagine there will be some type of data migration plan put in place.

**Comment by robsmall** [comment]
@rbstarbuck thanks!

The reason I am asking about this is we currently have important data stored in the application specific folder in GDrive for when users get a new phone and need to transfer data. We are trying to make a call on whether or not we need to/can implement a migration path to retrieve the data from the app specific folder via the Drive REST APIs or if we just need to declare bankruptcy with the data that is stored in the Drive APIs and move over to another solution.

It should be a small percentage of affected users (only those who don't update their app to the version that replaces the Drive API usage before breaking/losing their phone), but we are looking to enumerate our options.

Is there any more information we can receive on this topic? If not, we will likely need to abandon GDrive all together. Please let me know if I can provide any more information.

**Comment by rbstarbuck** [comment]
I wouldn't worry, Google places a high priority on data integrity and I seriously doubt a deprecation of Drive app data storage would move forward without a solid data migration plan in place. We still recommend moving to a non-Drive solution for app data to avoid a second migration effort later, but if it does become necessary there will be plenty of time and options for clients.

**Comment by robsmall** [comment]
Thanks! It sounds like there may be some documented plan in the future (before end of life-ing the app specific folder) for data migration, but that just hasn't been teased out yet. Would that be a fair summary?

**Comment by rbstarbuck** [comment]
Yes, if they sunset app data storage I'm certain they'll put a plan in place for migrating data.

**Comment by robsmall** [comment]
Thanks! Do you have any ideas on what the timelines/solutions may be?

**Comment by rbstarbuck** [comment]
None at all, I asked around and there hasn't been any advancement on this effort. It may not happen at all, if it does it's probably a way's away.
