### ISSUE TITLE
GoogleApiClient connection failed

### ISSUE THREAD

**Issue by Muran-Hu** [gsuitedevs/android-samples#49]
Hi all, 

When i running the demo, one issue appeared:

I choose my Google Account: muranhu@gmail.com to access Google Drive, but failed. Here is the log message:

> I/BaseDriveActivity: GoogleApiClient connection failed: ConnectionResult{statusCode=SIGN_IN_REQUIRED, resolution=PendingIntent{419fdaa8: android.os.BinderProxy@419cad20}, message=null}

![cf59d4ae-d1d6-4fab-a9a2-889f43fa5248](https://cloud.githubusercontent.com/assets/10492550/15998658/9b80eb26-3172-11e6-8137-e0131d06f6c6.png)

Is there something wrong or i missed something? Could you please share your advice here? TIA

Thanks Muran

**Comment by addgoa** [comment]
Same thing happens with me too

**Comment by Muran-Hu** [comment]
Is there anyone can help me?

**Comment by Muran-Hu** [comment]
@addgoa, is there any solution?

**Comment by Muran-Hu** [comment]
@addgoa, Please refer to the discussion ["not working"](https://github.com/googledrive/android-quickstart/issues/7).

**Comment by amrbrkt** [comment]
Any solutions ?!

**Comment by SlagbrandFrontwalker** [comment]
Same Issue happened for me like a month ago. Any sollutions?

**Comment by peswanibros** [comment]
Hi to resolve this issue go to the google api console from your gmail account. Here you will see a disable button in front of Google drive api. just right to that you will see a gear or setting button click on it and generate oAuth token. 

That's it!!

**Comment by broadxie2** [comment]
1. Create project at **https://console.developers.google.com** 
2. Enable **drive api**
3. Create **credentials** for your project (Add **keystore SHA-1** and **package name**)

Then, you can run the demo .

**Comment by surajitshome** [comment]
This will work once you create your Google API project and put your SHA-1 and Package name. 
And, Keep in mind that Your package must not conflict with others project in Google.
Hope this works.
Register your project in : https://console.developers.google.com
and Enable API once project credentials are all set.
-Surajit.
Happy Coding.

**Comment by ils-aashishj** [comment]
Still not working only getting statusCode=SIGN_IN_REQUIRED

**Comment by medaka** [comment]
The same problem has been occured in my environment.
Some of the features works properly but others do not.

I googled and found some articles in StackOverFlow like this
[how-to-get-driveid-of-created-folder-in-google-drive-android-api](http://stackoverflow.com/questions/22199537/how-to-get-driveid-of-created-folder-in-google-drive-android-api)
but it still doesn't work.

These features work well below:
- Create a file 
- Create a folder

But these features do not work below:
- Retrieve meta data
- Retrieve Contents

**Comment by medaka** [comment]
I solved the problem myself.
I've forget to set EXISTING_FOLDER_ID and EXISTING_FILE_ID described in the bottom of README.

However I think README is not enough to run this demo because we cannot find out what to set these constants..

**Comment by rodrigoGA** [comment]
+1

**Comment by mDroidd** [comment]
Do you need to create an OAuth token or an API Key?

Do you need to provide one of them in the applications AndroidManifest.xml?

**Comment by ChillarAnand** [comment]
Any updates on the issue?

**Comment by nishantsingh1814** [comment]
Add debug SHA key in Api cloud console  oAuth  instead of release SHA key

**Comment by asrivas** [comment]
You no longer need to set the EXISTING_FOLDER_ID and EXISTING_FILE_ID values. I have updated the README in https://github.com/gsuitedevs/android-samples/pull/78.

Please follow the authentication instructions here: https://developers.google.com/drive/android/get-started.
If you still have issues with sign in or specific activities (@medaka -- did you try to retrieve on a text file?), please file a separate issue.
