### ISSUE TITLE
Got issue while downloading file from google drive

### ISSUE THREAD

**Issue by ravi-vihaaInfotech** [gsuitedevs/android-samples#54]
I have created demo Application for google drive file sharing into my server. Below is my Process 

* Have enable google drive api in console
* Have connected googleApiClient
* Have fire intent for opening google drive file list

	IntentSender intentSender = Drive.DriveApi
        .newOpenFileActivityBuilder()
        .setMimeType(new String[]{"application/pdf",
                "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                "application/vnd.google-apps.spreadsheet",
                "application/vnd.google-apps.document",
                "application/vnd.google-apps.presentation"})

    startIntentSenderForResult(intentSender, REQUEST_CODE_OPENER, null, 0, 0, 0);

* And onActivityResult code and downloadFile code as below
	
	@Override
public void onActivityResult(int requestCode, int resultCode, Intent data) {
    super.onActivityResult(requestCode, resultCode, data);
    try {
        if (resultCode == RESULT_OK) {
            DriveId driveId = (DriveId) data.getParcelableExtra(OpenFileActivityBuilder.EXTRA_RESPONSE_DRIVE_ID);
            DriveFile selectedFile = driveId.asDriveFile();
         selectedFile.getMetadata(getGoogleApiClient()).setResultCallback(metadataRetrievedCallback);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}
ResultCallback<DriveResource.MetadataResult> metadataRetrievedCallback = new
        ResultCallback<DriveResource.MetadataResult>() {
            @Override
            public void onResult(DriveResource.MetadataResult result) {
                if (!result.getStatus().isSuccess()) {
                    AppLog.e("problem", "Problem while trying to fetch metadata");
                    return;
                }
                Metadata metadata = result.getMetadata();

                if (metadata.getTitle().contains(".")) {
                    fileName = metadata.getTitle();
                } else {
                    if (metadata.getMimeType().contains("application/pdf"))
                        fileName = metadata.getTitle() + ".pdf";
                    else if (metadata.getMimeType().contains("application/vnd.openxmlformats-officedocument.wordprocessingml.document"))
                        fileName = metadata.getTitle() + ".docx";
                    else if (metadata.getMimeType().contains("application/vnd.google-apps.spreadsheet"))
                        fileName = metadata.getTitle() + ".xls";
                    else if (metadata.getMimeType().contains("application/vnd.google-apps.presentation"))
                        fileName = metadata.getTitle() + ".pptx";
                    else if (metadata.getMimeType().contains("application/vnd.google-apps.document"))
                        fileName = metadata.getTitle() + ".txt";
                }
                new FileDownloadTask().execute();
            }
        };

private class FileDownloadTask extends AsyncTask<String, Void, String> {

    @Override
    protected void onPreExecute() {
        super.onPreExecute();
        progressDialog = ProgressDialog.show(FileExplorerActivity.this, "", true, false, null);
    }

    @Override
    protected String doInBackground(String... arg0) {
        downloadFileToSdCard();
        return null;
    }

    @Override
    protected void onPostExecute(String s) {
        if (progressDialog != null && progressDialog.isShowing()) {
            progressDialog.dismiss();
        }
        super.onPostExecute(s);
        Intent intent = new Intent();
        intent.putExtra("filePath", Const.DOC_PATH + "/" + fileName);
        setResult(RESULT_OK, intent);
        finish();
    }

    private void downloadFileToSdCard() {
        try {
            selectedFile.open(getGoogleApiClient(), DriveFile.MODE_READ_ONLY, null).setResultCallback(contentsOpenedCallback);
        } catch (Exception io) {
            io.printStackTrace();
        }
    }
}

ResultCallback<DriveApi.DriveContentsResult> contentsOpenedCallback =
        new ResultCallback<DriveApi.DriveContentsResult>() {
            @Override
            public void onResult(DriveApi.DriveContentsResult result) {
                if (!result.getStatus().isSuccess()) {
                    return;
                }

                try {

                    File dir = new File(Const.DOC_PATH);
                    if (dir.exists() == false) {
                        dir.mkdirs();
                    }
                    String fName = fileName;
                    File file = new File(dir, fName);
                    if (file.exists())
                        file.delete();

                    FileOutputStream fos = new FileOutputStream(file);
                    DriveContents driveContents = result.getDriveContents();
                    byte[] buffer = new byte[1024];
                    int bufferLength = 0;
                    InputStream inputStream = driveContents.getInputStream();
                    while ((bufferLength = inputStream.read(buffer)) > 0) {
                        fos.write(buffer, 0, bufferLength);
                    }
                    driveContents.discard(getGoogleApiClient());
                    fos.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        };

* Here in above “contentsOpenedCallback”  i got my issue 
* i got driveContents value null for drive file which has created in google drive
* have used cradle version 2.2.2
* have used compile 'com.google.android.gms:play-services:9.8.0'

**Comment by asrivas** [comment]
Are you still having this issue?

**Comment by asrivas** [comment]
DriveApi.DriveContentsResult has been deprecated, please let us know if you are still having issues with the new recommendation.
https://developers.google.com/android/reference/com/google/android/gms/drive/DriveApi.DriveContentsResult
