### ISSUE TITLE
CreateFileInAppFolderActivity

### ISSUE THREAD

**Issue by gcstang** [gsuitedevs/android-samples#61]
CreateFileInAppFolderActivity doesn't show how to upload anything no content is set on the Drive Contents.

**Comment by asrivas** [comment]
Yes, this demo activity specifically only creates a text file.
https://github.com/gsuitedevs/android-samples/blob/master/drive/demos/app/src/main/java/com/google/android/gms/drive/sample/demo/CreateFileInAppFolderActivity.java#L34

You can look at the Quickstart sample for a demo on how to upload an image file. 
 further:https://github.com/gsuitedevs/android-samples/blob/master/drive/quickstart/app/src/main/java/com/google/android/gms/drive/sample/quickstart/MainActivity.java
