### ISSUE TITLE
AppFolder is empty after reinstalling application

### ISSUE THREAD

**Issue by mark-torres** [gsuitedevs/android-samples#62]
Is this a bug? If I reinstall the application and check the app folder using the same credentials and account the query for the AppFolder children returns 0 elements.

**Comment by or-dvir** [comment]
same issue here!
this is super weird because it was working perfectly fine yesterday but now if i uninstall and reinstall my app then the file is not found

**Comment by asrivas** [comment]
Are you still having this issue?

**Comment by EbenezerGH** [comment]
@asrivas i am having this issue

**Comment by or-dvir** [comment]
Don't know... I gave up on Google drive api a long time ago due to this and many other problems

**Comment by asrivas** [comment]
Sorry to hear that, please let us know if you have any other issues with the samples
