### ISSUE TITLE
Access Google Drive with googleAPIClient is deprecated and not working anymore ?

### ISSUE THREAD

**Issue by phukhanhlee** [gsuitedevs/android-samples#67]
private void initGoogleAPI(){
		if (mGoogleApiClient == null) {
			mGoogleApiClient = new GoogleApiClient.Builder(this)
					.enableAutoManage(this,this)
					.addApi(Drive.API)
					.addScope(Drive.SCOPE_FILE)
					.addConnectionCallbacks(this)
					.build();

		}
	}

@Override
public void onConnected(@Nullable Bundle bundle) { -> not call anymore
}

And i see seem code demo has change ?

**Comment by asrivas** [comment]
Yes, please follow the updated code in:
https://github.com/gsuitedevs/android-samples/blob/master/drive/demos/app/src/main/java/com/google/android/gms/drive/sample/demo/BaseDemoActivity.java
