### ISSUE TITLE
Timeout on DriveResourceClient.getRootFolder()

### ISSUE THREAD

**Issue by NLLAPPS** [gsuitedevs/android-samples#68]
Is anyone watching this repo? I am unable to find issue tracker for Google play Services so I am keep posting here but not getting any response.

On some accounts `DriveResourceClient.getRootFolder()` does not complete the task. If I use `Tasks.await(..)` it timeouts even if I set `Tasks.await(task, 30, TimeUnit.MINUTES)`

Further more, on accounts with above issue
`new OpenFileActivityOptions.Builder()
                .setSelectionFilter(Filters.eq(SearchableField.MIME_TYPE, DriveFolder.MIME_TYPE))
                .setActivityTitle(title)`

is unable to load drive contents and either continuously shows loading icon or does not open at all.
I am unable to create this issue on my account but can provide contact details of users who reported it for further investigation.

Resetting/cleaning the cache of Google Play services fixes this issue and it comes back after a while.

**Comment by NLLAPPS** [comment]
Anyone?

**Comment by NLLAPPS** [comment]
Hi, is there any updates about this?

It looks like there was some sort of server side change that caused more and more accounts to be affected by the above issue.

I am using 15.0.1 and can redirect few of my affected users for investigation

**Comment by erickoledadevrel** [comment]
This issue tracker is meant for reporting bugs in the sample code. For general API support see the options here:

https://developers.google.com/drive/android/support
