### ISSUE TITLE
The file is a excel. Exception file isn't openable

### ISSUE THREAD

**Issue by kbboss** [gsuitedevs/android-samples#86]
**java.util.concurrent.ExecutionException: com.google.android.gms.common.api.ApiException: 10: This file is not openable.

06-28 17:54:06.697 17633-18261/com.google.android.gms.drive.sample.demo W/System.err:     at com.google.android.gms.tasks.Tasks.zzb(Unknown Source)
06-28 17:54:06.697 17633-18261/com.google.android.gms.drive.sample.demo W/System.err:     at com.google.android.gms.tasks.Tasks.await(Unknown Source)
06-28 17:54:06.698 17633-18261/com.google.android.gms.drive.sample.demo W/System.err:     at com.google.android.gms.drive.sample.demo.events.HcDriveUtil.await(HcDriveUtil.java:306)`**

### So far, I only open image type and txt, then another type can't be openable

**Comment by erickoledadevrel** [comment]
The file referenced in the error, `HcDriveUtil.java`, isn't a part of this repo. Was this a file you added to the sample? If so, please use one of the support channels instead:

https://developers.google.com/drive/android/support
